### ISSUE TITLE
Users lookup broken

### ISSUE THREAD

**Issue by thet** [bluedynamics/bda.plone.shop#66]
with bda.plone.shop (and bda.plone.productshop) on Plone 4.3, the user lookup is broken. Instead of the username something like this is displayed: ``<object object at 0x7fd704e09580>``

Example for documentByLine:

![screen shot 2016-05-04 at 11 39 03](https://cloud.githubusercontent.com/assets/170891/15010549/e056ee6c-11ec-11e6-8bab-2b6010818c45.png)

**Comment by agitator** [comment]
imho that's an issue in Plone 5 too

**Comment by rnixx** [comment]
This bug went in somewhen in p4.x, yes.

**Comment by rnixx** [comment]
This is probably a good place to start

https://github.com/bluedynamics/bda.plone.shop/blob/master/src/bda/plone/shop/user/configure.zcml

at the time the users stuff went into the shop there was heavy progress on plone.app.users, so chances are hight the something has been optimized until broken or so

**Comment by pcdummy** [comment]
I have been looking into this.

#### Debug

While debugging this i found that we use two different ``_marker`` in [PlonePAS.tools.memberdata.MemberDataTool](https://github.com/plone/Products.PlonePAS/blob/master/src/Products/PlonePAS/tools/memberdata.py#L26) and [Products.CMFCore.MemberDataTool.MemberData](https://github.com/plone/Products.CMFCore/blob/2.2/Products/CMFCore/MemberDataTool.py#L39), the value we see is the _marker from **PlonePAS** this is a **bug**.

When you change the _marker to be imported from CMFCore you get an error "no such property fullname", this is because we delete that property in ``portal_memberdata`` over ``memberdata_properties.xml``.

When you manualy readd this property over the CMI you get another error then **no such property location**, we also delete location from portal_memberdata, so i added that property too and it works.

The fields don't get displayed in @@personal-information.


#### Question

If found ``bda.plone.shop.user.userdata.UserDataSchemaAdapter`` this provides both fields, can we register that somehow as **sheet** for [PlonePAS memberdata L300](https://github.com/plone/Products.PlonePAS/blob/master/src/Products/PlonePAS/tools/memberdata.py#L300)

**Comment by pcdummy** [comment]
I just found http://docs.plone.org/4/en/old-reference-manuals/pluggable_authentication_service/properties-plugins.html looks like we need to implement that, will update the comment above.

**Comment by thet** [comment]
The PlonePAS bug should be fixed first.

The customization of userdata properties was done like in https://github.com/collective/collective.examples.userdata

If we need a custom properties plugin, then ok. The implementation looks quite easy. It sounds just not very extensible - it may conflict with other addons, if they provide their own userdata property adapters. But that's maybe negligible. 

So, go ahead! :)

**Comment by pcdummy** [comment]
PlonePAS pr is [here](https://github.com/plone/Products.PlonePAS/pull/18)

**Comment by thet** [comment]
@pcdummy PlonePAS merged. PR for bda.plone.shop up not ready yet?

**Comment by pcdummy** [comment]
Sorry, forgot to add a PR for this.

**Comment by pcdummy** [comment]
It works with Plone5 but i found a bug, the new Plugin must be last so this works and it doesn't get sorted in as the last one.
